const CartActionTypes = {
  ADD_POSITION: "ADD_POSITION",
  REMOVE_POSITION: "REMOVE_POSITION",
  DELETE_POSITION_FROM_CART: "DELETE_POSITION_FROM_CART",
  CHANGE_STATUS_TO_ORDERED: "CHANGE_STATUS_TO_ORDERED",
  REMOVE_SERVED_POSITIONS: "REMOVE_SERVED_POSITIONS",

  FETCH_POSITIONS_ORDERED_START: "FETCH_POSITIONS_ORDERED_START",
  FETCH_POSITIONS_ORDERED_SUCCESS: "FETCH_POSITIONS_ORDERED_SUCCESS",
  FETCH_POSITIONS_ORDERED_FAIL: "FETCH_POSITIONS_ORDERED_FAIL",

  FETCH_POSITIONS_SERVED_START: "FETCH_POSITIONS_SERVED_START",
  FETCH_POSITIONS_SERVED_SUCCESS: "FETCH_POSITIONS_SERVED_SUCCESS",
  FETCH_POSITIONS_SERVED_FAIL: "FETCH_POSITIONS_SERVED_FAIL",
};
export default CartActionTypes;
