const MenuActionTypes = {
  UPDATE_MENU: "UPDATE_MENU",
  TOGGLE_POPUP: "TOGGLE_POPUP",
  FETCH_MENU_START: "FETCH_MENU_START",
  FETCH_MENU_SUCCESS: "FETCH_MENU_SUCCESS",
  FETCH_MENU_FAIL: "FETCH_MENU_FAIL",
};

export default MenuActionTypes;
