const OrdersActionTypes = {
  FETCH_ORDERS_START: "FETCH_ORDERS_START",
  FETCH_ORDERS_SUCCESS: "FETCH_ORDERS_SUCCESS",
  FETCH_ORDERS_FAIL: "FETCH_ORDERS_FAIL",

  CHANGE_STATUS_TO_SERVED: "CHANGE_STATUS_TO_SERVED",
  REMOVE_SERVED: "REMOVE_SERVED",
  REMOVE_ORDERED: "REMOVE_ORDERED",
  ADD_NEW_ORDER: "ADD_NEW_ORDER",

  FETCH_SERVED_START: "FETCH_SERVED_START",
  FETCH_SERVED_SUCCESS: "FETCH_SERVED_SUCCESS",
  FETCH_SERVED_FAIL: "FETCH_SERVED_FAIL",
};

export default OrdersActionTypes;
